// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"
)

type Account struct {
	ID       int64     `json:"id"`
	Owner    string    `json:"owner"`
	Balance  int64     `json:"balance"`
	Currency string    `json:"currency"`
	CreateAt time.Time `json:"create_at"`
}

type Entry struct {
	ID        int64 `json:"id"`
	AccountID int64 `json:"account_id"`
	// 可以是正的或负的
	Amount   int64     `json:"amount"`
	CreateAt time.Time `json:"create_at"`
}

type Transfer struct {
	ID             int64 `json:"id"`
	FromAccountsID int64 `json:"from_accounts_id"`
	ToAccountsID   int64 `json:"to_accounts_id"`
	// 必须是正的
	Amount   int64     `json:"amount"`
	CreateAt time.Time `json:"create_at"`
}
